### PR TITLE
AnaMaria day2 

### PR DESCRIPTION
**Pull request by AnaMG21**
sentence changed in temp file

### CODE REVIEW

**Review by AnaMG21 — COMMENTED** [review]
all good

**Review by AnaMG21 — COMMENTED** [review]
talk functionality checked

**Review by mhaydarov — APPROVED** [review]
ok

**Review by mhaydarov — APPROVED** [review]
good

**Review by alibekler — APPROVED** [review]

**Review by hiltas73 — APPROVED** [review]

**Review by alibekler — APPROVED** [review]
ok

**Review by hiltas73 — APPROVED** [review]

**Review by hiltas73 — APPROVED** [review]

**Review by hiltas73 — APPROVED** [review]

**Review by hiltas73 — APPROVED** [review]

**Pull request closed without merging**
