### PR TITLE
Case insensitive username login cases has been modified and added

### PR DESCRIPTION
**Pull request by Harun1233**
Username should be case sensitive, accoring to this scenario, new test script has been added

### CODE REVIEW

**Review by mhaydarov — CHANGES_REQUESTED** [review]
Hi Harun, could you please delete the .idea folder (in your branch)and then re-create the pull request? I'm trying to avoid .idea folder to be sent to GitHub.

couple of days ago we have updated the master branch and think you were working on outdated one.

**Comment by Harun1233** [comment]
Hi merdan, my project is updated, I have updated it tonight, should I delete the totally idea folder ?

**Comment by mhaydarov** [comment]
Harun, I will try to delete it .idea and .iml

**Review by mhaydarov — APPROVED** [review]

**Review by AnaMG21 — APPROVED** [review]
ok

**Pull request merged**
