### PR TITLE
Contacts Fuctionality 

### PR DESCRIPTION
**Pull request by aysultan**
Contacts Fuctionlity updated

### CODE REVIEW

**Review by mhaydarov — APPROVED** [review]
Good job

**Review by hiltas73 — APPROVED** [review]
ok

**Review by AnaMG21 — APPROVED** [review]
all good

**Comment by Harun1233** [comment]
Good Job

**Review by hiltas73 — APPROVED** [review]
okok

**Review by hiltas73 — APPROVED** [review]
ok

**Review by hiltas73 — APPROVED** [review]
ok

**Review by hiltas73 — APPROVED** [review]
ok

**Review by hiltas73 — APPROVED** [review]
ok

**Review by hiltas73 — APPROVED** [review]
ok

**Review by hiltas73 — APPROVED** [review]

**Review by Harun1233 — APPROVED** [review]
all good

**Review by Harun1233 — APPROVED** [review]
good job

**Review by Harun1233 — APPROVED** [review]
good job

**Review by Harun1233 — APPROVED** [review]
good job

**Review by Harun1233 — APPROVED** [review]
good job

**Review by Harun1233 — APPROVED** [review]
good job

**Pull request merged**
