### PR TITLE
 talk , calendar functionalities

### PR DESCRIPTION
**Pull request by AnaMG21**
adding talk functionality and calendar

### CODE REVIEW

**Review by mhaydarov — APPROVED** [review]
great stuff

**Review by Harun1233 — APPROVED** [review]
ok

**Review by Harun1233 — APPROVED** [review]
good job

**Review by Harun1233 — APPROVED** [review]
exellent work

**Review by Harun1233 — APPROVED** [review]
that drove me crazy

**Review by Harun1233 — APPROVED** [review]
OMG

**Review by Harun1233 — APPROVED** [review]
Wow

**Review by Harun1233 — APPROVED** [review]
keep doing this

**Review by Harun1233 — APPROVED** [review]
My english has finished

**Review by hiltas73 — APPROVED** [review]
ok

**Review by Harun1233 — APPROVED** [review]
ok

**Review by Harun1233 — APPROVED** [review]
ok

**Review by Harun1233 — APPROVED** [review]
ok

**Pull request merged**
